MCU = RP2040
BOOTLOADER = rp2040

VIA_ENABLE = yes
VIAL_ENABLE = yes

RGB_MATRIX_ENABLE = no
RGBLIGHT_ENABLE = no
LED_MATRIX_ENABLE = no
BACKLIGHT_ENABLE = no
OLED_ENABLE = no
ENCODER_ENABLE = no
AUDIO_ENABLE = no

LTO_ENABLE = yes
